<!DOCTYPE html>
<html>
<head>
<title>%title%</title>
<meta http-equiv='Content-Type' content="text/html; charset=UTF-8">
<head>
<script src="../assets/js/snamik.js"></script>
<script><!--
%scripts%
// --></script>
</head>

<frameset  rows='0,*,60' border=0>
  <frame name=topframe src=top.html marginwidth=1 marginheight=1 scrolling=no frameborder=no noresize>
  <frameset  cols='0,*,0,270' border=0>
    <frame name=mleft src=mleft.html marginwidth=1 marginheight=1 scrolling=Yes frameborder=no noresize>
       <frameset name=sets rows='0,*,0' border=1>
       <frame name=gameframe src=start.html marginwidth=0 marginheight=0 scrolling=Yes frameborder=1>
       <frame name=left src=start.html marginwidth=10 marginheight=5 scrolling=Yes frameborder=1>
       <frame name=privat marginwidth=10 marginheight=5 scrolling=Yes frameborder=1>
    </frameset>
    <frame name=write marginwidth=1 marginheight=1 scrolling=no frameborder=no noresize>
    <frame name=users src=users.html marginwidth=1 marginheight=1 scrolling=Yes frameborder=no noresize>      
  </frameset>
  <frame name=chat src=chat.html marginwidth=1 marginheight=1 scrolling=no frameborder=no noresize>
</frameset>

</html>